# Generated by Django 4.0.5 on 2022-06-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default='2022-06-30 04:48'),
        ),
    ]
